name: Another

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  antother-tests:

    runs-on: self-hosted

    steps:
    - name: ANOTHER TEST
      run: echo "another test"