name: Another

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  antother-tests:

    runs-on: self-hosted

    steps:
    - name: ANOTHER TEST
      run: echo "another test"