name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - name: Change to web Directory
      run: cd /var/www/html/this-app
    - name: Git Fetch
      run: git fetch
    - name: Git Pull
      run: git pull
    - name: addind some env vars
      run: export PATH=/usr/node/bin:$PATH && export NODE_OPTIONS=--max_old_space_size=1024
    - name: Setup npm
      run: npm run prod
    - name: Test
      run: echo "Done!"
