name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    #- name: Checkout code
    #  uses: actions/checkout@v3
    - name: Change to web Directory
      run: cd /var/www/html/this-app
    - name: Git Fetch
      run: git fetch
    - name: Git Pull
      run: git pull
    - name: Test
      run: echo "Done!"
