name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - name: Change to Web Directory
      run: |
        cd /var/www/html/this-app
        git config --global --add safe.directory /var/www/html/this-app
        git fetch
        git pull
        npm run dev
