name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    #- name: Checkout code
    #  uses: actions/checkout@v3
    - name: Change to web Directory
      working-directory: /var/www/html/this-app
    - name: Test
      run: echo "Done!"
