name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - name: Change to Web Directory
      run: |
        cd /var/www/html/this-app
        git config --global --add safe.directory /var/www/html/this-app
        git fetch
        git pull
        npm run dev
    #- name: addind some env vars
    #  run: export PATH=/usr/node/bin:$PATH && export NODE_OPTIONS=--max_old_space_size=1024
    - name: Test
      run: echo "Done!"
