name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    -name: Change to web Directory
      run: cd /var/www/html/this-app
    -name: Update Directory
      run: git status
      run: git fetch
      run: git status
      run: git pull
    - name: Test
      run: echo "Done!"
