name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - name: UPDATE APPLICATION - RUN MIGRATIONS - COMPILE DEPENDENCIES
      run: |
        cd /var/www/html/this-app
        git config --global --add safe.directory /var/www/html/this-app
        git fetch
        git pull
        php artisan migrate:fresh
        php artisan db:seed
        npm run dev
        echo "logged off"
